sudo: required
services:
  - docker

before_install:
  - docker build -t jabro888/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jabro888/react-test npm test -- --coverage

after_succes:
  - docker build -t jabro888/multi-client ./client
  - docker build -t jabro888/multi-nginx ./nginx
  - docker build -t jabro888/multi-server ./server
  - docker build -t jabro888/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jabro888/multi-client
  - docker push jabro888/multi-nginx
  - docker push jabro888/multi-server
  - docker push jabro888/multi-worker


